### ISSUE TITLE
Request more than 50000 rows?

### ISSUE THREAD

**Issue by Gabriel-p** [cds-astro/cds.cdsclient#1]
I am not able to request more than 50000 rows. Example:

    python vizquery.py -source=I/350/gaiaedr3 -c="100.0-50.0" -c.rs=43200 "Gmag<19" > temp.dat

Using the `-out.max` parameter:

    python vizquery.py -source=I/350/gaiaedr3 -out.max -c="100.0-50.0" -c.rs=43200 "Gmag<19" > temp.dat

results in a single line queried.    

I've tried modifying the `DEFAULT_LIMIT` but the resulting query is still limited to 50000 rows.

**Comment by gilleslandais** [comment]
Hi -
You are true, there is a default  limit on the number of records returned in a VizieR votable (the format used in background). But this limit can be overpassed with the "-out.max=xxx" option.
You have just to add a limit in your query:

python vizquery.py -source=I/350/gaiaedr3 -out.max=999999 -c="100.0-50.0" -c.rs=43200 "Gmag<19"

**Comment by Gabriel-p** [comment]
Thank you Gilles, I was using the `out.max` parameter wrong, it works now so I'm closing the issue.

If you don't mind, one more question: can I select which columns to query? The default command requests many columns I'm not interested in which I'd like to avoid, and does not include for example the `_x, _y` columns that one can get from the web service.

**Comment by gilleslandais** [comment]
Yes you can select the column: (-out option)
eg: python vizquery.py -source=I/350/gaiaedr3 -out.max=999999 -c="100.0-50.0" -c.rs=43200 "Gmag<19" -out=_RA_ICRS,_DE_ICRS,Source,Plx,Gmag

**Comment by Gabriel-p** [comment]
Thank you again! Last question I swear: how can I select the output format? I'd like the 999 ascii filled format which is easier to process.

Is there a document with all these commands somewhere?

**Comment by gilleslandais** [comment]
You can go to the ASU document which list the paremeters: http://cdsarc.u-strasbg.fr/doc/asu-summary.htx
The outputs available are :  -mime=tsv|votable|ascii 
see also the help: python vizquery.py  -h (but I just note that formats are not good in the help page: i will fix )

**Comment by Gabriel-p** [comment]
Thank you again Gilles!
