### ISSUE TITLE
Large region is returned incomplete

### ISSUE THREAD

**Issue by Gabriel-p** [cds-astro/cds.cdsclient#2]
I'm trying to download a region of 10 deg length (box size) with the command:

    $ python vizquery.py -source=I/350/gaiaedr3 -out.max=10000000 -c="119.527-60.800" -c.bd=10 "Gmag<19" -out=EDR3Name,_x,_y,RA_ICRS,DE_ICRS,Source,Plx,e_Plx,PM,pmRA,e_pmRA,pmDE,e_pmDE,FG,e_FG,Gmag,e_Gmag,FBP,e_FBP,BPmag,e_BPmag,FRP,e_FRP,RPmag,e_RPmag,BP-RP > temp.dat

This is what I'm getting:

![Figure_1](https://user-images.githubusercontent.com/6054951/131398119-980d5615-63b0-49c1-a049-e9417faff6b3.png)

**Comment by gilleslandais** [comment]
Your query is too large for vizquery and the common vizier interface.
You reach a timeout limit (not reported by vizquery yet)

I suggest you to use TAPVizieR : http://tapvizier.u-strasbg.fr/adql/?I/350

SELECT EDR3Name,RA_ICRS,DE_ICRS,Source,Plx , DISTANCE(POINT('ICRS',119.527, -60.800), POINT('ICRS',RA_ICRS, DE_ICRS))
FROM "I/350/gaiaedr3" 
WHERE "Gmag">19 AND
1=CONTAINS(POINT('ICRS',RA_ICRS,DE_ICRS), BOX('ICRS', 119.527, -60.800, 10., 10.))

Unfortunately TAPvizieR (available also with topcat or pyVO) doesn't support _x,_y projection output (only distance is available)

**Comment by Gabriel-p** [comment]
Thank you very much Gilles. I'm trying to download the data using TAPVizieR but it is also timing out. This is my query:

```
-- output format : csv
SELECT "I/350/gaiaedr3".RA_ICRS,  "I/350/gaiaedr3".DE_ICRS,  "I/350/gaiaedr3".Plx,  "I/350/gaiaedr3".e_Plx,  "I/350/gaiaedr3".PM,  "I/350/gaiaedr3".pmRA,  "I/350/gaiaedr3".e_pmRA,
"I/350/gaiaedr3".pmDE,  "I/350/gaiaedr3".e_pmDE,  "I/350/gaiaedr3".Gmag,  "I/350/gaiaedr3".e_Gmag,  "I/350/gaiaedr3".e_BPmag,  "I/350/gaiaedr3".e_RPmag,  "I/350/gaiaedr3"."BP-RP",  "I/350/gaiaedr3".EDR3Name
FROM "I/350/gaiaedr3"
WHERE 1=CONTAINS(POINT('ICRS',"I/350/gaiaedr3".RA_ICRS,"I/350/gaiaedr3".DE_ICRS), BOX('ICRS', 119.527, -60.800, 10., 10.))
AND "I/350/gaiaedr3".Gmag<19
AND "I/350/gaiaedr3".Plx>2
```

and the link with the results http://tapvizier.u-strasbg.fr:8080/TAPVizieR/tap/async/1630417708990/results/result

In any case, this is not related to this code so I'm  closing the issue.

Thank you again!

**Comment by gilleslandais** [comment]
fixed!
but unfortunately, I think that your jobs has to be restarted...

**Comment by Gabriel-p** [comment]
Downloaded! I can't thank you enough Gilles!

Cheers
